autoaug: true
autoaug_target: false
batch_size: 9
class_balance: true
cpu: false
crop_size: 512,256
data_dir: ./data/Cityscapes/data
data_dir_target: ./data/Cityscapes/data
data_list: ./dataset/cityscapes_list/train.txt
data_list_target: ./dataset/cityscapes_list/train.txt
droprate: 0.2
fp16: false
gpu_ids: 0,1,2
ignore_label: 255
input_size: 1280,640
input_size_target: 1024,512
is_training: false
iter_size: 1
lambda_adv_target1: 0.0
lambda_adv_target2: 0.0
lambda_kl_target: 0.0
lambda_me_target: 0.0
lambda_seg: 0.5
learning_rate: 0.0001
learning_rate_D: 0.0001
log_dir: ./log
max_value: 7.0
model: DeepLab
momentum: 0.9
norm_style: gn
not_restore_last: false
num_classes: 19
num_steps: 100000
num_steps_stop: 100000
num_workers: 2
often_balance: true
only_hard_label: 80.0
power: 0.9
random_mirror: false
random_scale: false
random_seed: 1234
restore_from: ./snapshots/SE_GN_batchsize2_1024x512_pp_ms_me0_classbalance7_kl0.1_lr2_drop0.1_seg0.5/GTA5_25000.pth
save_num_images: 2
save_pred_every: 5000
set: train
snapshot_dir: ./snapshots/1280x640_restore_ft_GN_batchsize9_512x256_pp_ms_me0_classbalance7_kl0_lr1_drop0.2_seg0.5_BN_80_255_0.8_Noaug
sync_bn: false
target: cityscapes
tensorboard: true
train_bn: true
use_se: true
warm_up: 5000.0
weight_decay: 0.0005
